{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mikrotik-credentials",
    "namespace": "infra"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mikrotik-credentials",
        "namespace": "infra"
      }
    },
    "encryptedData": {
      "password": "AgA2dIOXA8fZKh0+YTSWzRk9btgjdHkVD+TRr8tfs7R58DRKN07ZbAHXmkZ/cmkefDQBX1clOyZgRzsoxFm+sPeINah2fHld86USl+tNGAib17LYzcPY4zC4wXihpTCadELCDdORx7Zhepcvt4++rGbhq4ai3k8MpPI/bnPelpjpfqrmt/56EmzPDOpBW4goFsLuQW0voPYiTi7M3hPO79ZlgxyF35gB+Ex2t7P/z4R4HDtxN2SULnJ4HKGGXppFe5AUMgMGZ3MTeiXqqdihs3/2JOf3bzcgucNYYDNsIC8Mk06XvQiquwBU1DZ5pk/ll3C5bOrPorIJwAv2nvMhwfoT3suo0MxklQLsfAdIpM/XVuK6iyLM9yTC7ZdIcZLeHsLkyLXuWpOyKfW6lp/mVBdIboL5vYxBtaUoU740VArvHcizR8kCxkjIFsMAkMk5dIlxdJF8eMS5eiDspjXmwpdprzwgpR5nd/lhdJQSy4Fdiv7TldfLjqunrOcdBlD+DmoD3soPfpxI+RPpH6g5VpZCRFYOGaR1oeWd2KChoJu63sj5WgLjOAxF0MVbC8V0ipGtSiqczK5pg0K+5TjjBJPs7hnw3rSmVdtxIa6GCwaTE2jpJZ7e2LuIBuRpgKguS7/xwLM4CajuOrib5kQivKBnXkjh0HBy5dpfDRYfxD7yyj9lWvzjgQ3beH8ukYXKEl9hQqvJ0ZTG4RuVNxw=",
      "username": "AgB/OwcTK2uh2EsC2B5ug6cV4sxUVZiZdlHUUkRPpRJ1KWPgFjStH0l6pJzlpH6Y1bDMItaOVuXNCpbJEkeqY6OGKmOxZ42Hqmw6KjmlrdWOG5c2T1XRVFP9fshG58rOeu5xNp6dgRDvMXtClELPi3ofPyy9P7BNLoMrn0XdZXS1ifHW2ZG9hTcBl1IqmkWPa3tAd7a6ftWxTAzsWCr122UjSzCz80Il+axiuPw1UgD74/lYsgKpztJG60UZZPpR6B5cgXsjc4Ac1MyDS1z1QXBeZsQc2CuvdK9kKQfU3dI6yb+h0FZOr5B/zDG9jOYQG5Auq8r5rFKX/BXuLCByWN3ryEr8Axp9W6FBxPYiN3FQ0NLjGs3sjGdaM+IAvw6OK92UIvh5lwCAwfhrWbclX2wLCmOO3XiucA/ateZfI2GQgPQJCe9v1uNlGnekBXVk5P5z46hGAZdonU6xhCkiu9YKG8mzk7HXxGXtad0w0y6CqhWzoAOAFKeb2dIes/U7luQNnx/0OkZ94JP3A6Fnnxqg57ri4VA4mmGbWVlwIPAENSg118crVJr5sbP1e2GcqsG7eGdpyI4raRsmy2MM6A9ttibBBHD/LKKvt/PP4zv1rM8bEDu8GZr10j43ejMQvEsc0Zuc3ubdDrzpHalhtN8R7IWaB2/wgJBkVxsHptPPM/ruJks8h2gqR1NlHPT1nbyxVivn/g=="
    }
  }
}
