apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infra/sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
