apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-ks.yaml
  - cilium-bgp-ks.yaml
  - longhorn-prereqs-ks.yaml
  - longhorn-ks.yaml
  - multus-ks.yaml
  - kubevirt-ks.yaml
  - cnao-ks.yaml
