apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-longhorn
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: core-longhorn-prereqs
  prune: false
  path: ./kubernetes/core/longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
