---
# SOPS-Konfiguration f端r k8s-homelab-gitops-v2
# Alle Secrets in kubernetes/ werden mit Age verschl端sselt.
# Public key: age1z6080dvy3sphcl4jq86ue78xns0ap2age97237yrzh87cmzsmfcqh43xee
#
# Verschl端sseln:  sops --encrypt --in-place <datei.yaml>
# Entschl端sseln:  sops --decrypt <datei.yaml>
# Bearbeiten:     sops <datei.yaml>
creation_rules:
  # path_regex matcht gegen absoluten Pfad (auch Windows-Backslash-Variante)
  - path_regex: kubernetes[/\\].*\.yaml$
    age: age1z6080dvy3sphcl4jq86ue78xns0ap2age97237yrzh87cmzsmfcqh43xee
