apiVersion: v1
kind: ConfigMap
metadata:
  name: macvtap-custom-config
  namespace: cluster-network-addons
data:
  DP_MACVTAP_CONF: |
    [
      {"name":"vlan5",   "lowerDevice":"bond0.5",   "mode":"bridge","capacity":2},
      {"name":"vlan10",  "lowerDevice":"bond0.10",  "mode":"bridge","capacity":2},
      {"name":"vlan30",  "lowerDevice":"bond0.30",  "mode":"bridge","capacity":2},
      {"name":"vlan40",  "lowerDevice":"bond0.40",  "mode":"bridge","capacity":2},
      {"name":"vlan50",  "lowerDevice":"br50",      "mode":"bridge","capacity":2},
      {"name":"vlan60",  "lowerDevice":"bond0.60",  "mode":"bridge","capacity":2},
      {"name":"vlan100", "lowerDevice":"bond0.100", "mode":"bridge","capacity":2},
      {"name":"vlan200", "lowerDevice":"bond0.200", "mode":"bridge","capacity":2}
    ]
