apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan50-transit
  namespace: infra
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan50-transit",
      "type": "bridge",
      "bridge": "br50",
      "ipam": {}
    }
