apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: router
  namespace: infra
spec:
  running: false
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {"name":"vlan5-wan","namespace":"infra"},
            {"name":"vlan50-transit","namespace":"infra"}
          ]
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 1Gi
        devices:
          autoattachPodInterface: false
          interfaces:
            - name: wan
              bridge: {}
            - name: transit
              bridge: {}
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
      networks:
        - name: wan
          multus:
            networkName: infra/vlan5-wan
        - name: transit
          multus:
            networkName: infra/vlan50-transit
      volumes:
        - name: rootdisk
          containerDisk:
            image: ghcr.io/berndinox/edge-router:2026.02
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: router-cloudinit
